### ISSUE TITLE
Old rules are not removed from /etc/prometheus/rules

### ISSUE THREAD

**Issue by madeinoz67** [ernestas-poskus/ansible-prometheus#39]
rules are not removed from the /etc/prometheus/rules directory if they are removed from role variables or are renamed.

**Comment by ernestas-poskus** [comment]
This one is tricky since Ansible is stateless when you remove or rename you don't have any previous state of the previous object. Nevertheless, it is possible to do this manually in wrapping playbook. 

Moreover, a new variable could be introduced which goes through the list and then removes those rules but I am reluctant to introduce this because one must not forget to add a rule to the list after removing/renaming rule.

**Comment by madeinoz67** [comment]
I think it will be a manual removal for the time being, I'll just have to remember to check after I run the role
